### ISSUE TITLE
New Permission Setting

### ISSUE THREAD

**Issue by JustOneMoreBlock** [BAMdevelopment/GlobalBan#4]
Hello,

I was wondering if you could add in a permission node that will allow us to set limits on banning a player.

We would give this permission to newer staff while they're training.

The permission would be similar to:
globalban.ban.<duration>
- The time will be in seconds.
- This will be a max time.

For example:
globalban.ban.86400
- This time is in seconds and converts to 24 Hours (1 day)
- This is the max time, so if something happens the staff can ban upto 24 hours. 
They can do like 1 Hour or 6 hour bans. If it's on the same player, it should add to total up to a day ban.

**Comment by fr34kyn01535** [comment]
I won't do that, but feel free to add it yourself.
